	
	<title>Welcome to CodeIgniter</title>
<div id="container">
	<h1>Welcome to iStudyBooks!</h1>

	<div id="body">
		<p>The page you are looking at is being generated by CodeIgniter.</p>
	</div>

</div>